
[cmake]
    min_ver = "3.21"

[project]
    name = "Demo"
    cxx_standard = "17"

[package_manager]
    use_cpm = false
    use_vcpkg = true

[precompiled_header]
    enabled = true
    # `pch_file` path is relative the current project directory.
    pch_file = "build/pch/precompile.h"

[platform_support]
    windows = true
    posix = true

[main_module]
    name = "demo"
    # choose between "library" or "executable"
    type = "executable"
    # effective only if precompiled_header is enable.
    use_pch = true
    # effective only if windows platform is enabled.
    use_msvc_static_analysis = true

[test_support]
    enabled = true
    # Unused. Currently only support doctest
    # framework = "doctest"
