
[cmake]
    min_ver = "3.28"

[project]
    name = "Demo"
    cxx_standard = "17"

[package_manager]
    use_cpm = false
    use_vcpkg = true

[precompiled_header]
    enabled = false

[platform_support]
    windows = true
    posix = true

[main_module]
    name = "demo"
    # choose between "library", "interface" or "executable"
    type = "executable"
    # effective only if precompiled_header is enable, and module type is not interface.
    use_pch = false

[test_support]
    enabled = true
    # Unused. Currently only support doctest
    # framework = "doctest"
