
[cmake]
    min_ver = "3.11"

[project]
    name = "Demo"
    cxx_standard = "14"

[precompiled_header]
    enabled = true
    # `pch_file` path is relative the current project directory.
    pch_file = "build/pch/precompile.h"

[platform_support]
    windows = true
    posix = true

[main_module]
    name = "demo"
    # choose between "library" or "executable"
    type = "executable"
    # effective only if precompiled_header is enable.
    use_pch = true
    # effective only if windows platform is enabled.
    use_msvc_static_analysis = true
